### PR TITLE
feature: add buildflag

### PR DESCRIPTION
**Pull request by skaman**
From original cordova fastlane plugin https://github.com/bamlab/fastlane-plugin-cordova/issues/37
I just merged the pull request https://github.com/bamlab/fastlane-plugin-cordova/pull/38

I'm not a ruby developer (neither was who did the original pull request into the fastlane-plugin-cordova. So we did our best 👯‍♂️ 

In any case, if someone need it, this fix work in my case.

Cheers

### CODE REVIEW

**Comment by janpio** [comment]
Awesome @skaman, then we are all in one boat re not having any idea what we are doing with ruby ;)

I am following what @blackholegalaxy has been doing over at the repo - I wanted to wait until the PR was merged and confirmed working though.

You didn't encounter any problems?

**Comment by blackholegalaxy** [comment]
You can confirm it works by pointing to my repo and branch on the fastlane PluginFile `gem 'fastlane-plugin-cordova', :git => "git://github.com/blackholegalaxy/fastlane-plugin-cordova.git", :branch => "feat/add-buildflag"`

**Comment by skaman** [comment]
> Awesome @skaman, then we are all in one boat re not having any idea what we are doing with ruby ;)
> 
> I am following what @blackholegalaxy has been doing over at the repo - I wanted to wait until the PR was merged and confirmed working though.
> 
> You didn't encounter any problems?

Nope, everything went fine. Some small conflict to solve but all of them was elementary stuff.

**Comment by blackholegalaxy** [comment]
@skaman just rebased you only have one commit to take and adapt :)

**Pull request closed without merging**
