### PR TITLE
Fix Android release build path

### PR DESCRIPTION
**Pull request by isair**
Fixed for the latest version (v4) of Ionic.

### CODE REVIEW

**Comment by isair** [comment]
Apologies, I don't usually work with Ionic + Cordova so I made a quick
assumption there.

I believe it is perfectly acceptable for a new major version of this plugin
to drop support for an older major Cordova version. Semver makes these
scenarios easier to manage. Though it should be well documented which
version of Cordova works with which version of this plugin.

**Comment by janpio** [comment]
Good point. Can you maybe add the necessary information to the `README`?

**Comment by janpio** [comment]
I took the liberty to commit a README and version change to your branch so I can cleanly merge this.

Github seems to have helpfully removed your actual changes though... so I will just quickly create a new PR of my own and commit from there. Sorry :/

**Comment by isair** [comment]
No worries. Thanks for the update!

**Pull request closed without merging**
